import { ClientChannelSummary, ClientProfile, Ticket, TicketStatus } from '@/types/domain';
import { formatBdt, formatLocalizedNumber } from './localized-format';

type ClientLanguage = ClientProfile['defaultLanguage'];

type TicketFilter = 'all' | 'open' | TicketStatus;

const englishStatusLabels: Record<TicketStatus, string> = {
  open: 'Open',
  assigned: 'Assigned',
  waiting_client: 'Waiting on you',
  reopened: 'Reopened',
  resolved: 'Resolved',
};

const banglaStatusLabels: Record<TicketStatus, string> = {
  open: 'খোলা',
  assigned: 'টিমের কাছে',
  waiting_client: 'আপনার সিদ্ধান্ত দরকার',
  reopened: 'আবার খোলা হয়েছে',
  resolved: 'সমাধান হয়েছে',
};

const mixedStatusLabels: Record<TicketStatus, string> = {
  open: 'Open',
  assigned: 'Team assigned',
  waiting_client: 'Apnar decision dorkar',
  reopened: 'Reopened',
  resolved: 'Resolved',
};

const englishFilterLabels: Record<TicketFilter, string> = {
  all: 'All',
  open: 'Open',
  assigned: 'Assigned',
  waiting_client: 'Waiting on you',
  reopened: 'Reopened',
  resolved: 'Resolved',
};

const banglaFilterLabels: Record<TicketFilter, string> = {
  all: 'সব',
  open: 'খোলা',
  assigned: 'টিমের কাছে',
  waiting_client: 'আপনার সিদ্ধান্ত দরকার',
  reopened: 'আবার খোলা হয়েছে',
  resolved: 'সমাধান হয়েছে',
};

const mixedFilterLabels: Record<TicketFilter, string> = {
  all: 'All',
  open: 'Open',
  assigned: 'Team assigned',
  waiting_client: 'Decision dorkar',
  reopened: 'Reopened',
  resolved: 'Resolved',
};

function normalizeLanguage(language?: ClientLanguage): ClientLanguage {
  if (language === 'bangla' || language === 'english' || language === 'mixed') return language;
  return 'mixed';
}

function baseCopy(language: ClientLanguage) {
  if (language === 'bangla') {
    return {
      locale: 'bn-BD',
      nav: {
        aria: 'ক্লায়েন্ট পোর্টাল',
        overview: 'ওভারভিউ',
        tickets: 'টিকিট',
        knowledge: 'নলেজ',
        data: 'ডাটা',
        setup: 'সেটআপ',
      },
      common: {
        refresh: 'রিফ্রেশ',
        signOut: 'সাইন আউট',
        loading: 'লোড হচ্ছে',
        copy: 'কপি',
        noMessages: 'মেসেজ নেই',
      },
      dashboard: {
        eyebrow: 'ক্লায়েন্ট ড্যাশবোর্ড',
        supportCoverage: 'সাপোর্ট কভারেজ',
        coverageTitle: (connected: number) =>
          `${formatLocalizedNumber(connected, 'bangla')} / ${formatLocalizedNumber(3, 'bangla')} কাস্টমার চ্যানেলে AI সহায়তা চালু আছে`,
        coverageDescription:
          'Messenger, WhatsApp এবং web widget আলাদা করে ট্র্যাক করা হচ্ছে, যেন কোন চ্যানেল লাইভ আর কোথায় সেটআপ দরকার তা বোঝা যায়।',
        clientAccount: 'ক্লায়েন্ট অ্যাকাউন্ট',
        loadingAccount: 'অ্যাকাউন্ট লোড হচ্ছে',
        contactPending: 'যোগাযোগের তথ্য বাকি',
        channelsOnline: 'চ্যানেল অনলাইন',
        setupNeeded: 'সেটআপ দরকার',
        conversations: 'কথোপকথন',
        handledByAi: 'AI দ্বারা হ্যান্ডেল করা',
        containment: 'কন্টেইনমেন্ট',
        noHandoffNeeded: 'হ্যান্ডঅফ লাগেনি',
        openTickets: 'খোলা টিকিট',
        salesProtected: 'সেলস সুরক্ষিত',
        bdtEstimate: 'BDT অনুমান',
        channelVisibility: 'চ্যানেল দৃশ্যমানতা',
        channelConversations: 'কথোপকথন',
        openWidget: 'উইজেট খুলুন',
        recentTickets: 'সাম্প্রতিক টিকিট',
        delegate: 'ডেলিগেট',
        noTicketsYet: 'এখনও কোনো টিকিট নেই',
        recentConversations: 'সাম্প্রতিক কথোপকথন',
      },
      tickets: {
        eyebrow: 'ক্লায়েন্ট ডেলিগেশন',
        title: 'টিকিট',
        queueEyebrow: 'টিকিট কিউ',
        queueTitle: 'কাস্টমার ইস্যু যেগুলোতে আপনার সিদ্ধান্ত দরকার',
        queueDescription: 'ডেলিগেটেড কথোপকথন রিভিউ করুন, স্টেট আপডেট করুন, আর সাপোর্ট টিমকে একই তথ্য দিন।',
        open: 'খোলা',
        p1: 'P1',
        status: 'স্টেটাস',
        delegatedTickets: 'ডেলিগেটেড টিকিট',
        noTickets: 'কোনো টিকিট নেই',
        ticketDetail: 'টিকিট বিস্তারিত',
        selectTicket: 'বিস্তারিত দেখতে একটি টিকিট নির্বাচন করুন',
        raisedFromConversation: 'কাস্টমার কথোপকথন থেকে তৈরি',
        currentState: 'বর্তমান অবস্থা',
        raised: 'তোলা হয়েছে',
        lastUpdated: 'শেষ আপডেট',
        protectedSale: 'সুরক্ষিত সেল',
        raisedReason: 'কেন এই টিকিট তৈরি হয়েছে',
        suggestedReply: 'প্রস্তাবিত উত্তর',
        timeline: 'টিকিট টাইমলাইন',
        loadingTimeline: 'টাইমলাইন লোড হচ্ছে',
        noTimeline: 'এখনও কোনো টাইমলাইন ইভেন্ট নেই',
        customerConversation: 'কাস্টমার কথোপকথন',
        transcriptPending: 'লোড হলে কথোপকথনের ট্রান্সক্রিপ্ট এখানে দেখা যাবে',
        protectedEstimate: (amount: number) => `${formatBdt(amount, 'bangla')} সুরক্ষিত অনুমান`,
      },
      dataSources: {
        eyebrow: 'লাইভ বিজনেস ডাটা',
        title: 'ডাটা সোর্স',
        googleSheet: 'Google Sheet',
        connectedTitle: 'প্রোডাক্ট ও অর্ডার ডাটা সংযুক্ত',
        connectTitle: 'প্রোডাক্ট ও অর্ডার ডাটা সংযুক্ত করুন',
        lastSyncLine: (lastSync: string, productMinutes: number, orderMinutes: number) =>
          `শেষ সিঙ্ক: ${lastSync}. প্রোডাক্ট ${formatLocalizedNumber(productMinutes, 'bangla')} মিনিট এবং অর্ডার ${formatLocalizedNumber(orderMinutes, 'bangla')} মিনিট ফ্রেশ থাকে।`,
        products: 'প্রোডাক্ট',
        orders: 'অর্ডার',
        sheetLink: 'Google Sheet লিংক',
        sourceName: 'সোর্স নাম',
        sheetUrl: 'Google Sheet URL',
        productsTab: 'প্রোডাক্ট ট্যাব',
        ordersTab: 'অর্ডার ট্যাব',
        syncMinutes: 'সিঙ্ক মিনিট',
        productFreshness: 'প্রোডাক্ট ফ্রেশনেস',
        orderFreshness: 'অর্ডার ফ্রেশনেস',
        save: 'সেভ',
        syncNow: 'এখন সিঙ্ক',
        syncStatus: 'সিঙ্ক স্টেটাস',
        lastResult: 'শেষ ফলাফল',
        productsImported: 'প্রোডাক্ট ইমপোর্ট',
        ordersImported: 'অর্ডার ইমপোর্ট',
        notSynced: 'সিঙ্ক হয়নি',
        noSku: 'SKU নেই',
        noProducts: 'কোনো প্রোডাক্ট সিঙ্ক হয়নি',
        noOrders: 'কোনো অর্ডার সিঙ্ক হয়নি',
        saved: 'Google Sheet সোর্স সেভ হয়েছে।',
        syncComplete: (products: number, orders: number) =>
          `সিঙ্ক সম্পন্ন: ${formatLocalizedNumber(products, 'bangla')} প্রোডাক্ট এবং ${formatLocalizedNumber(orders, 'bangla')} অর্ডার ইমপোর্ট হয়েছে।`,
        loadError: 'ডাটা সোর্স লোড করা যায়নি।',
        saveError: 'Google Sheet সোর্স সেভ করা যায়নি।',
        syncError: 'Google Sheet সিঙ্ক করা যায়নি।',
      },
      knowledge: {
        eyebrow: 'বিজনেস নলেজ',
        title: 'নলেজ বেস',
        approvedAnswers: 'অনুমোদিত উত্তর',
        commandTitle: (count: number) =>
          `${formatLocalizedNumber(count, 'bangla')} প্রকাশিত এন্ট্রি আপনার AI সাপোর্ট এজেন্ট ব্যবহার করতে পারে`,
        commandDescription: 'এগুলো এখন অনুমোদিত কাস্টমার-ফেসিং তথ্য। জমা দেওয়া আপডেট অপারেশন টিম প্রকাশ করা পর্যন্ত রিভিউতে থাকে।',
        published: 'প্রকাশিত',
        requests: 'রিকোয়েস্ট',
        publishedKnowledge: 'প্রকাশিত নলেজ',
        searchPlaceholder: 'এন্ট্রি খুঁজুন',
        approved: 'অনুমোদিত',
        suggestEdit: 'এডিট সাজেস্ট করুন',
        emptyEntries: 'এই ভিউতে কোনো প্রকাশিত এন্ট্রি নেই',
        addRequest: 'নলেজ রিকোয়েস্ট যোগ করুন',
        new: 'নতুন',
        editingRequest: (title: string) => `${title} এর জন্য এডিট রিকোয়েস্ট`,
        titleLabel: 'টাইটেল',
        answer: 'উত্তর',
        keywords: 'কিওয়ার্ড',
        category: 'ক্যাটাগরি',
        urgency: 'আর্জেন্সি',
        normal: 'নরমাল',
        urgent: 'আর্জেন্ট',
        businessNote: 'বিজনেস নোট',
        submitRequest: 'রিকোয়েস্ট জমা দিন',
        submitEdit: 'এডিট জমা দিন',
        submitting: 'জমা হচ্ছে',
        clear: 'ক্লিয়ার',
        updateRequests: 'আপডেট রিকোয়েস্ট',
        status: 'স্টেটাস',
        feedback: 'ফিডব্যাক',
        noRequests: 'এখনও কোনো আপডেট রিকোয়েস্ট নেই',
        requestSubmitted: 'নলেজ রিকোয়েস্ট জমা হয়েছে।',
        editSubmitted: 'এডিট রিকোয়েস্ট জমা হয়েছে।',
        loadError: 'নলেজ লোড করা যায়নি।',
        submitError: 'রিকোয়েস্ট জমা দেওয়া যায়নি।',
        titleError: 'টাইটেল কমপক্ষে ২ অক্ষর হতে হবে।',
        answerError: 'উত্তর কমপক্ষে ২ অক্ষর হতে হবে।',
        keywordError: 'কমপক্ষে একটি কিওয়ার্ড দিন।',
      },
      onboarding: {
        eyebrow: 'ক্লায়েন্ট অনবোর্ডিং',
        title: 'আপনার বিজনেস সেটআপ করুন',
        brief: 'আপনার ওয়ার্কস্পেসের জন্য বিজনেস কনটেক্সট, চ্যানেল সেটআপ পথ, এবং প্রথম নলেজ নোট শেয়ার করুন।',
        steps: { profile: 'প্রোফাইল', channels: 'চ্যানেল', knowledge: 'নলেজ' },
        businessProfile: 'বিজনেস প্রোফাইল',
        businessCategory: 'বিজনেস ক্যাটাগরি',
        businessCategoryPlaceholder: 'Fashion, dental clinic, electronics',
        customerChannels: 'কাস্টমার চ্যানেল',
        websiteUrl: 'Website URL',
        facebookPageUrl: 'Facebook page URL',
        continueChannels: 'চ্যানেলে যান',
        saving: 'সেভ হচ্ছে...',
        channelSetup: 'চ্যানেল সেটআপ',
        whatsappSetupPath: 'WhatsApp সেটআপ পথ',
        whatsappSelf: 'আমি সেটআপ তথ্য দেব',
        assisted: 'আমার সাথে সেটআপ করুন',
        skipNow: 'এখন বাদ দিন',
        whatsappSupportNumber: 'WhatsApp সাপোর্ট নম্বর',
        facebookSetupPath: 'Facebook সেটআপ পথ',
        facebookOauth: 'Facebook OAuth দিয়ে সংযুক্ত করুন',
        facebookOauthRequested: 'Facebook OAuth সেটআপ রিকোয়েস্ট করা হয়েছে।',
        facebookPageId: 'Facebook Page ID',
        websiteNoted: 'Website channel noted. ড্যাশবোর্ডে web widget প্রস্তুত থাকবে।',
        continueKnowledge: 'নলেজে যান',
        skipChannelSetup: 'চ্যানেল সেটআপ বাদ দিন',
        firstKnowledge: 'প্রথম নলেজ নোট',
        knowledgeTitle: 'নলেজ টাইটেল',
        businessKnowledge: 'বিজনেস নলেজ',
        keywords: 'কিওয়ার্ড',
        finish: 'অনবোর্ডিং শেষ করুন',
        finishing: 'শেষ হচ্ছে...',
        skipKnowledge: 'এখন নলেজ বাদ দিন',
        missingSession: 'ক্লায়েন্ট সেশন পাওয়া যায়নি।',
        selectChannel: 'কমপক্ষে একটি কাস্টমার চ্যানেল নির্বাচন করুন।',
        profileError: 'বিজনেস প্রোফাইল সেভ করা যায়নি।',
        channelError: 'চ্যানেল সেটআপ সেভ করা যায়নি।',
        skipError: 'চ্যানেল সেটআপ বাদ দেওয়া যায়নি।',
        finishError: 'অনবোর্ডিং শেষ করা যায়নি।',
      },
      statusLabels: banglaStatusLabels,
      filterLabels: banglaFilterLabels,
      channelStatus: (status: ClientChannelSummary['status']) => {
        if (status === 'connected') return 'সংযুক্ত';
        if (status === 'available') return 'ব্যবহারযোগ্য';
        if (status === 'contact_only') return 'শুধু কন্টাক্ট';
        return 'সেটআপ দরকার';
      },
      eventTitle: (eventType: string) => {
        if (eventType === 'ticket.created') return 'টিকিট তৈরি হয়েছে';
        if (eventType === 'ticket.status_updated') return 'স্টেটাস আপডেট হয়েছে';
        if (eventType === 'ticket.assignee_updated') return 'ওনার আপডেট হয়েছে';
        if (eventType === 'ticket.comment_added') return 'অপারেশন নোট যোগ হয়েছে';
        return eventType.replaceAll('.', ' ');
      },
    };
  }

  if (language === 'english') {
    return {
      locale: 'en',
      nav: {
        aria: 'Client portal',
        overview: 'Overview',
        tickets: 'Tickets',
        knowledge: 'Knowledge',
        data: 'Data',
        setup: 'Setup',
      },
      common: {
        refresh: 'Refresh',
        signOut: 'Sign out',
        loading: 'Loading',
        copy: 'Copy',
        noMessages: 'No messages',
      },
      dashboard: {
        eyebrow: 'Client dashboard',
        supportCoverage: 'Support coverage',
        coverageTitle: (connected: number) =>
          `AI assistance is active across ${formatLocalizedNumber(connected, 'english')} of ${formatLocalizedNumber(3, 'english')} customer channels`,
        coverageDescription:
          'Messenger, WhatsApp, and the web widget are tracked separately so your team can see which channels are live, which need setup, and where customers are already talking.',
        clientAccount: 'Client account',
        loadingAccount: 'Loading account',
        contactPending: 'Contact details pending',
        channelsOnline: 'Channels online',
        setupNeeded: 'Setup needed',
        conversations: 'Conversations',
        handledByAi: 'Handled by AI',
        containment: 'Containment',
        noHandoffNeeded: 'No handoff needed',
        openTickets: 'Open Tickets',
        salesProtected: 'Sales Protected',
        bdtEstimate: 'BDT estimate',
        channelVisibility: 'Channel visibility',
        channelConversations: 'conversations',
        openWidget: 'Open widget',
        recentTickets: 'Recent tickets',
        delegate: 'Delegate',
        noTicketsYet: 'No tickets yet',
        recentConversations: 'Recent conversations',
      },
      tickets: {
        eyebrow: 'Client delegation',
        title: 'Tickets',
        queueEyebrow: 'Ticket queue',
        queueTitle: 'Customer issues waiting for client decision',
        queueDescription: 'Review delegated conversations, update ownership state, and keep the support team aligned on resolution.',
        open: 'Open',
        p1: 'P1',
        status: 'Status',
        delegatedTickets: 'Delegated tickets',
        noTickets: 'No tickets',
        ticketDetail: 'Ticket detail',
        selectTicket: 'Select a ticket to view details',
        raisedFromConversation: 'Raised from customer conversation',
        currentState: 'Current state',
        raised: 'Raised',
        lastUpdated: 'Last updated',
        protectedSale: 'Protected sale',
        raisedReason: 'Why this ticket was raised',
        suggestedReply: 'Suggested reply',
        timeline: 'Ticket timeline',
        loadingTimeline: 'Loading timeline',
        noTimeline: 'No timeline events yet',
        customerConversation: 'Customer conversation',
        transcriptPending: 'Conversation transcript will appear here when loaded',
        protectedEstimate: (amount: number) => `${formatBdt(amount, 'english')} protected estimate`,
      },
      dataSources: {
        eyebrow: 'Live business data',
        title: 'Data Sources',
        googleSheet: 'Google Sheet',
        connectedTitle: 'Product and order data is connected',
        connectTitle: 'Connect product and order data',
        lastSyncLine: (lastSync: string, productMinutes: number, orderMinutes: number) =>
          `Last sync: ${lastSync}. Products stay fresh for ${formatLocalizedNumber(productMinutes, 'english')} minutes; orders stay fresh for ${formatLocalizedNumber(orderMinutes, 'english')} minutes.`,
        products: 'Products',
        orders: 'Orders',
        sheetLink: 'Google Sheet link',
        sourceName: 'Source name',
        sheetUrl: 'Google Sheet URL',
        productsTab: 'Products tab',
        ordersTab: 'Orders tab',
        syncMinutes: 'Sync minutes',
        productFreshness: 'Product freshness',
        orderFreshness: 'Order freshness',
        save: 'Save',
        syncNow: 'Sync now',
        syncStatus: 'Sync status',
        lastResult: 'Last result',
        productsImported: 'Products imported',
        ordersImported: 'Orders imported',
        notSynced: 'Not synced',
        noSku: 'No SKU',
        noProducts: 'No products synced',
        noOrders: 'No orders synced',
        saved: 'Google Sheet source saved.',
        syncComplete: (products: number, orders: number) =>
          `Sync complete: ${formatLocalizedNumber(products, 'english')} products and ${formatLocalizedNumber(orders, 'english')} orders imported.`,
        loadError: 'Unable to load data sources.',
        saveError: 'Unable to save Google Sheet source.',
        syncError: 'Unable to sync Google Sheet.',
      },
      knowledge: {
        eyebrow: 'Business knowledge',
        title: 'Knowledge Base',
        approvedAnswers: 'Approved answers',
        commandTitle: (count: number) =>
          `${formatLocalizedNumber(count, 'english')} published entries available to your AI support agent`,
        commandDescription: 'These are the customer-facing facts currently approved for replies. Submitted updates stay in review until the operations team publishes them.',
        published: 'Published',
        requests: 'Requests',
        publishedKnowledge: 'Published knowledge',
        searchPlaceholder: 'Search entries',
        approved: 'approved',
        suggestEdit: 'Suggest edit',
        emptyEntries: 'No published entries match this view',
        addRequest: 'Add knowledge request',
        new: 'New',
        editingRequest: (title: string) => `Editing request for ${title}`,
        titleLabel: 'Title',
        answer: 'Answer',
        keywords: 'Keywords',
        category: 'Category',
        urgency: 'Urgency',
        normal: 'Normal',
        urgent: 'Urgent',
        businessNote: 'Business note',
        submitRequest: 'Submit request',
        submitEdit: 'Submit edit',
        submitting: 'Submitting',
        clear: 'Clear',
        updateRequests: 'Update requests',
        status: 'Status',
        feedback: 'Feedback',
        noRequests: 'No update requests yet',
        requestSubmitted: 'Knowledge request submitted.',
        editSubmitted: 'Edit request submitted.',
        loadError: 'Unable to load knowledge.',
        submitError: 'Unable to submit request.',
        titleError: 'Title must be at least 2 characters.',
        answerError: 'Answer must be at least 2 characters.',
        keywordError: 'Add at least one keyword.',
      },
      onboarding: {
        eyebrow: 'Client onboarding',
        title: 'Set up your business',
        brief: 'Share the business context, channel setup path, and first knowledge notes for your workspace.',
        steps: { profile: 'profile', channels: 'channels', knowledge: 'knowledge' },
        businessProfile: 'Business profile',
        businessCategory: 'Business category',
        businessCategoryPlaceholder: 'Fashion, dental clinic, electronics',
        customerChannels: 'Customer channels',
        websiteUrl: 'Website URL',
        facebookPageUrl: 'Facebook page URL',
        continueChannels: 'Continue to channels',
        saving: 'Saving...',
        channelSetup: 'Channel setup',
        whatsappSetupPath: 'WhatsApp setup path',
        whatsappSelf: 'I will provide setup details',
        assisted: 'Set it up with me',
        skipNow: 'Skip for now',
        whatsappSupportNumber: 'WhatsApp support number',
        facebookSetupPath: 'Facebook setup path',
        facebookOauth: 'Connect with Facebook OAuth',
        facebookOauthRequested: 'Facebook OAuth setup requested.',
        facebookPageId: 'Facebook Page ID',
        websiteNoted: 'Website channel noted. The dashboard will keep the web widget ready.',
        continueKnowledge: 'Continue to knowledge',
        skipChannelSetup: 'Skip channel setup',
        firstKnowledge: 'First knowledge notes',
        knowledgeTitle: 'Knowledge title',
        businessKnowledge: 'Business knowledge',
        keywords: 'Keywords',
        finish: 'Finish onboarding',
        finishing: 'Finishing...',
        skipKnowledge: 'Skip knowledge for now',
        missingSession: 'Client session is missing.',
        selectChannel: 'Select at least one customer channel.',
        profileError: 'Unable to save business profile.',
        channelError: 'Unable to save channel setup.',
        skipError: 'Unable to skip channel setup.',
        finishError: 'Unable to finish onboarding.',
      },
      statusLabels: englishStatusLabels,
      filterLabels: englishFilterLabels,
      channelStatus: (status: ClientChannelSummary['status']) => {
        if (status === 'connected') return 'Connected';
        if (status === 'available') return 'Available';
        if (status === 'contact_only') return 'Contact only';
        return 'Needs setup';
      },
      eventTitle: (eventType: string) => {
        if (eventType === 'ticket.created') return 'Ticket raised';
        if (eventType === 'ticket.status_updated') return 'Status updated';
        if (eventType === 'ticket.assignee_updated') return 'Owner updated';
        if (eventType === 'ticket.comment_added') return 'Operations note added';
        return eventType.replaceAll('.', ' ');
      },
    };
  }

  return {
    locale: 'en',
    nav: {
      aria: 'Client portal',
      overview: 'Overview',
      tickets: 'Tickets',
      knowledge: 'Knowledge',
      data: 'Data',
      setup: 'Setup',
    },
    common: {
      refresh: 'Refresh',
      signOut: 'Sign out',
      loading: 'Loading',
      copy: 'Copy',
      noMessages: 'No messages',
    },
    dashboard: {
      eyebrow: 'Client dashboard',
      supportCoverage: 'Support coverage',
      coverageTitle: (connected: number) =>
        `${formatLocalizedNumber(connected, 'mixed')} of ${formatLocalizedNumber(3, 'mixed')} customer channels with AI assistance active`,
      coverageDescription:
        'Messenger, WhatsApp, ar web widget alada track kora hocche, jate live channel, setup-needed channel, ar customer traffic clear thake.',
      clientAccount: 'Client account',
      loadingAccount: 'Account loading',
      contactPending: 'Contact details pending',
      channelsOnline: 'Channels online',
      setupNeeded: 'Setup needed',
      conversations: 'Conversations',
      handledByAi: 'AI handled',
      containment: 'Containment',
      noHandoffNeeded: 'Handoff lageni',
      openTickets: 'Open Tickets',
      salesProtected: 'Sales Protected',
      bdtEstimate: 'BDT estimate',
      channelVisibility: 'Channel visibility',
      channelConversations: 'conversations',
      openWidget: 'Open widget',
      recentTickets: 'Recent tickets',
      delegate: 'Delegate',
      noTicketsYet: 'Ekhono ticket nei',
      recentConversations: 'Recent conversations',
    },
    tickets: {
      eyebrow: 'Client delegation',
      title: 'Tickets',
      queueEyebrow: 'Ticket queue',
      queueTitle: 'Customer issue jekhane client decision dorkar',
      queueDescription: 'Delegated conversations review korun, state update korun, ar support team ke aligned rakhun.',
      open: 'Open',
      p1: 'P1',
      status: 'Status',
      delegatedTickets: 'Delegated tickets',
      noTickets: 'Ticket nei',
      ticketDetail: 'Ticket detail',
      selectTicket: 'Details dekhte ekta ticket select korun',
      raisedFromConversation: 'Customer conversation theke raised',
      currentState: 'Current state',
      raised: 'Raised',
      lastUpdated: 'Last updated',
      protectedSale: 'Protected sale',
      raisedReason: 'Ei ticket keno raised hoyeche',
      suggestedReply: 'Suggested reply',
      timeline: 'Ticket timeline',
      loadingTimeline: 'Timeline loading',
      noTimeline: 'Ekhono timeline event nei',
      customerConversation: 'Customer conversation',
      transcriptPending: 'Load hole conversation transcript ekhane dekha jabe',
      protectedEstimate: (amount: number) => `${formatBdt(amount, 'mixed')} protected estimate`,
    },
    dataSources: {
      eyebrow: 'Live business data',
      title: 'Data Sources',
      googleSheet: 'Google Sheet',
      connectedTitle: 'Product ar order data connected',
      connectTitle: 'Product ar order data connect korun',
      lastSyncLine: (lastSync: string, productMinutes: number, orderMinutes: number) =>
        `Last sync: ${lastSync}. Products ${formatLocalizedNumber(productMinutes, 'mixed')} minutes fresh thake; orders ${formatLocalizedNumber(orderMinutes, 'mixed')} minutes fresh thake.`,
      products: 'Products',
      orders: 'Orders',
      sheetLink: 'Google Sheet link',
      sourceName: 'Source name',
      sheetUrl: 'Google Sheet URL',
      productsTab: 'Products tab',
      ordersTab: 'Orders tab',
      syncMinutes: 'Sync minutes',
      productFreshness: 'Product freshness',
      orderFreshness: 'Order freshness',
      save: 'Save',
      syncNow: 'Sync now',
      syncStatus: 'Sync status',
      lastResult: 'Last result',
      productsImported: 'Products imported',
      ordersImported: 'Orders imported',
      notSynced: 'Not synced',
      noSku: 'No SKU',
      noProducts: 'Ekhono product sync hoyni',
      noOrders: 'Ekhono order sync hoyni',
      saved: 'Google Sheet source saved.',
      syncComplete: (products: number, orders: number) =>
        `Sync complete: ${formatLocalizedNumber(products, 'mixed')} products ar ${formatLocalizedNumber(orders, 'mixed')} orders imported.`,
      loadError: 'Data sources load kora jayni.',
      saveError: 'Google Sheet source save kora jayni.',
      syncError: 'Google Sheet sync kora jayni.',
    },
    knowledge: {
      eyebrow: 'Business knowledge',
      title: 'Knowledge Base',
      approvedAnswers: 'Approved answers',
      commandTitle: (count: number) =>
        `${formatLocalizedNumber(count, 'mixed')} published entries apnar AI support agent use korte parbe`,
      commandDescription: 'Egulo currently approved customer-facing facts. Submitted updates operations team publish kora porjonto review e thake.',
      published: 'Published',
      requests: 'Requests',
      publishedKnowledge: 'Published knowledge',
      searchPlaceholder: 'Search entries',
      approved: 'approved',
      suggestEdit: 'Suggest edit',
      emptyEntries: 'Ei view e kono published entry match koreni',
      addRequest: 'Add knowledge request',
      new: 'New',
      editingRequest: (title: string) => `${title} er jonno edit request`,
      titleLabel: 'Title',
      answer: 'Answer',
      keywords: 'Keywords',
      category: 'Category',
      urgency: 'Urgency',
      normal: 'Normal',
      urgent: 'Urgent',
      businessNote: 'Business note',
      submitRequest: 'Submit request',
      submitEdit: 'Submit edit',
      submitting: 'Submitting',
      clear: 'Clear',
      updateRequests: 'Update requests',
      status: 'Status',
      feedback: 'Feedback',
      noRequests: 'Ekhono update request nei',
      requestSubmitted: 'Knowledge request submitted.',
      editSubmitted: 'Edit request submitted.',
      loadError: 'Knowledge load kora jayni.',
      submitError: 'Request submit kora jayni.',
      titleError: 'Title at least 2 characters hote hobe.',
      answerError: 'Answer at least 2 characters hote hobe.',
      keywordError: 'At least ekta keyword add korun.',
    },
    onboarding: {
      eyebrow: 'Client onboarding',
      title: 'Apnar business setup korun',
      brief: 'Workspace er jonno business context, channel setup path, ar first knowledge notes share korun.',
      steps: { profile: 'profile', channels: 'channels', knowledge: 'knowledge' },
      businessProfile: 'Business profile',
      businessCategory: 'Business category',
      businessCategoryPlaceholder: 'Fashion, dental clinic, electronics',
      customerChannels: 'Customer channels',
      websiteUrl: 'Website URL',
      facebookPageUrl: 'Facebook page URL',
      continueChannels: 'Continue to channels',
      saving: 'Saving...',
      channelSetup: 'Channel setup',
      whatsappSetupPath: 'WhatsApp setup path',
      whatsappSelf: 'Ami setup details provide korbo',
      assisted: 'Amar sathe setup korun',
      skipNow: 'Skip for now',
      whatsappSupportNumber: 'WhatsApp support number',
      facebookSetupPath: 'Facebook setup path',
      facebookOauth: 'Facebook OAuth diye connect korun',
      facebookOauthRequested: 'Facebook OAuth setup requested.',
      facebookPageId: 'Facebook Page ID',
      websiteNoted: 'Website channel noted. Dashboard web widget ready rakhbe.',
      continueKnowledge: 'Continue to knowledge',
      skipChannelSetup: 'Skip channel setup',
      firstKnowledge: 'First knowledge notes',
      knowledgeTitle: 'Knowledge title',
      businessKnowledge: 'Business knowledge',
      keywords: 'Keywords',
      finish: 'Finish onboarding',
      finishing: 'Finishing...',
      skipKnowledge: 'Skip knowledge for now',
      missingSession: 'Client session missing.',
      selectChannel: 'At least ekta customer channel select korun.',
      profileError: 'Business profile save kora jayni.',
      channelError: 'Channel setup save kora jayni.',
      skipError: 'Channel setup skip kora jayni.',
      finishError: 'Onboarding finish kora jayni.',
    },
    statusLabels: mixedStatusLabels,
    filterLabels: mixedFilterLabels,
    channelStatus: (status: ClientChannelSummary['status']) => {
      if (status === 'connected') return 'Connected';
      if (status === 'available') return 'Available';
      if (status === 'contact_only') return 'Contact only';
      return 'Setup needed';
    },
    eventTitle: (eventType: string) => {
      if (eventType === 'ticket.created') return 'Ticket raised';
      if (eventType === 'ticket.status_updated') return 'Status updated';
      if (eventType === 'ticket.assignee_updated') return 'Owner updated';
      if (eventType === 'ticket.comment_added') return 'Operations note added';
      return eventType.replaceAll('.', ' ');
    },
  };
}

export function getClientPortalCopy(language?: ClientLanguage) {
  return baseCopy(normalizeLanguage(language));
}

export function priorityTone(priority: Ticket['priority']) {
  if (priority === 'P1') return 'coral';
  if (priority === 'P2') return 'amber';
  return 'blue';
}
